/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestImport } from './routes/test'
import { Route as SelectionImport } from './routes/selection'
import { Route as ResultImport } from './routes/result'
import { Route as IndexImport } from './routes/index'
import { Route as CustomizeKanaSetImport } from './routes/customize-kana.$set'

// Create/Update Routes

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const SelectionRoute = SelectionImport.update({
  id: '/selection',
  path: '/selection',
  getParentRoute: () => rootRoute,
} as any)

const ResultRoute = ResultImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CustomizeKanaSetRoute = CustomizeKanaSetImport.update({
  id: '/customize-kana/$set',
  path: '/customize-kana/$set',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultImport
      parentRoute: typeof rootRoute
    }
    '/selection': {
      id: '/selection'
      path: '/selection'
      fullPath: '/selection'
      preLoaderRoute: typeof SelectionImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/customize-kana/$set': {
      id: '/customize-kana/$set'
      path: '/customize-kana/$set'
      fullPath: '/customize-kana/$set'
      preLoaderRoute: typeof CustomizeKanaSetImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/selection': typeof SelectionRoute
  '/test': typeof TestRoute
  '/customize-kana/$set': typeof CustomizeKanaSetRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/selection': typeof SelectionRoute
  '/test': typeof TestRoute
  '/customize-kana/$set': typeof CustomizeKanaSetRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/selection': typeof SelectionRoute
  '/test': typeof TestRoute
  '/customize-kana/$set': typeof CustomizeKanaSetRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/result' | '/selection' | '/test' | '/customize-kana/$set'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/result' | '/selection' | '/test' | '/customize-kana/$set'
  id:
    | '__root__'
    | '/'
    | '/result'
    | '/selection'
    | '/test'
    | '/customize-kana/$set'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultRoute: typeof ResultRoute
  SelectionRoute: typeof SelectionRoute
  TestRoute: typeof TestRoute
  CustomizeKanaSetRoute: typeof CustomizeKanaSetRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultRoute: ResultRoute,
  SelectionRoute: SelectionRoute,
  TestRoute: TestRoute,
  CustomizeKanaSetRoute: CustomizeKanaSetRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/result",
        "/selection",
        "/test",
        "/customize-kana/$set"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/result": {
      "filePath": "result.tsx"
    },
    "/selection": {
      "filePath": "selection.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/customize-kana/$set": {
      "filePath": "customize-kana.$set.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
